[pytest]
addopts = -q -ra --strict-markers --maxfail=1
markers =
    login : login test cases
    sanity1: Run sanity1 test cases
    sanity2: Run sanity2 test cases
    sanity3: test
    activities: activity suite
    test_3: custom bucket